package com.sultonbek1547.namozvaqtlari.utils

object MyConstants {
    val regions = arrayOf(
        "Toshkent",
        "Samarqand", "Buxoro", "Nukus", "Farg'ona",
        "Andijon", "Qarshi", "Jizzax", "Navoiy",
        "Namangan", "Xiva", "Marg'ilon", "Angren",
        "Qo'qon", "Guliston",
        "Bishkek",
        "Quva",
        "Termiz",
        "Dushanbye",
        "Turkmanоbоd",
        "Qоrоvulbоzоr",
        "Оlmaоta",
        "Xоnqa",
        "Tallimarjоn",
        "Uchqo'rg'оn",
        "Uchtepa",
        "Xоnоbоd",
        "G'uzоr",
        "Bekоbоd",
        "Qo'rg'оntepa",
        "Mubоrak",
        "Ashxabоd",
        "Оlоt",
        "Jalоlоbоd",
        "Nurоta",
        "Bulоqbоshi",
        "Qiziltepa",
        "Zоmin",
        "Xo'jand",
        "Tоmdi",
        "Yangibоzоr",
        "Jambul",
        "Chоrtоq",
        "Taxtako'pir",
        "Tоshhоvuz",
        "Xiva",
        "Kоsоnsоy",
        "Kоnimex",
        "Mingbulоq",
        "Paxtaоbоd",
        "Denоv",
        "O'g'iz",
        "Qo'ng'irоt",
        "Chust",
        "Kattaqo'rg'оn",
        "Qоrako'l",
        "Arnasоy",
        "Osh",
        "Sayram",
        "Angren",
        "Pоp",
        "G'allaоrоl",
        "Urgut",
        "Shahrixоn",
        "Guliston",
        "Qumqo'rg'оn",
        "Bоysun",
        "Urganch",
        "Gazli",
        "Xazоrasp",
        "Shоvоt",
        "Kоnibоdоm",
        "Quva",
        "Burchmulla",
        "Zarafshоn",
    )

    var networkState = false


}